### ISSUE TITLE
REQUEST: Change example in Set-SnipeitAsset

### ISSUE THREAD

**Issue by chillinglucifer** [snazy2000/SnipeitPS#153]
As seen in #60 

In the Set-SnipeitAsset file, the example reads: 

`Set-SnipeitAsset -id 1 -status_id 1 -model_id 1 -name "Machine1" -CustomValues = @{ "_snipeit_os_5 = "Windows 10 Pro" }`

This is incorrectly entered, either because many changes weren't reflected, or just oversight as you guys have better things to do (which is obviously understandable) 

I had to perform lots of trial and error as I was trying to figure it out (namely, I'm using the script with many custom fields and needed to know how I would go about using that).

It should read, (and maybe include an example of using multiple custom fields wouldn't hurt),

`Set-SnipeitAsset -id 1 -status_id 1 -model_id 1 -name "Machine1" -customfields @{ "_snipeit_os_5" = "Windows 10 Pro" ; "_snipeit_os_version" = "1909" }`

Wasn't sure how to go about this so I submitted this issue. I'm not SUPER familiar with GitHub yet, so if there is a way to suggest changes, even if they are formatting/example changes, I would appreciate being pointed in the right direction so I could request or submit those myself.

Thank you, and have a great day.

**Comment by PetriAsi** [comment]
Thanks for pointing out that mistake.  And yes, there's need for better examples and documentation. So I you can help with it, it more than welcome. 

For basic workflow for making changes and pull request you can [use this](https://opensource.com/article/19/7/create-pull-request-github)

Some additions :  When creating branch for you changes use descriptive name and clone directly from  upstream/develop branch  :

git checkout -b update/better-examples upstream/develop

All changes are going in to develop branch first,  so that way it's easier to keep up with upstream.

Pushing is still done to your fork
git push origin update/better-examples
