### ISSUE TITLE
Password required when making new user

### ISSUE THREAD

**Issue by bmangia2** [snazy2000/SnipeitPS#265]
## Context
When creating a new user with:
`
New-Snipeituser -first_name Snipe -last_name Test -username stest@mindex.com -activated $false -phone "9999" -ldap_import $false`

I get back the error:
```
Write-Error: C:\Program Files\WindowsPowerShell\Modules\SnipeitPS\1.10.220\Public\New-SnipeitUser.ps1:148
Line 148:
        $result = Invoke-SnipeitMethod @Parameters     
        password -------- {The password field is required.}
```
I checked over the documentation and it lists password as non-mandatory. The only way I found to get around it while testing was to add:
`-ldap_import $true`
(it should be noted that my domain is not synced to SnipeIT)

After checking through some old Issues I found one where you listed:
`password_confirmation = $password`

If I'm understanding this properly then when I make the user I should also add
`-password password`
to my new user line?

I apologize if this is self explanatory as I'm new to scripting but hopefully you can help clarify this for me and it may help someone in the future too.

## My Environment

* SnipitPS Module version used: Latest
* Operating System and PowerShell version: Wind 10, PowerShell 7
* Snipe It version: Latest

**Comment by PetriAsi** [comment]
As snipe-it documentation [shows](https://snipe-it.readme.io/reference/users-2) password and password_confirmation are required by api when creating new user. Password_confirmation is added by SnipeitPS so that that's not needed when using this module.

![image](https://user-images.githubusercontent.com/8735148/160816737-139da24e-0069-4948-bcc6-576f33d18ce9.png)

**Comment by bmangia2** [comment]
Awesome thanks for the feedback! This helped a lot!
